name: flutter_easy_routing
description: "Flutter Easy Routing - Navigation Make Easy - Use it Easy"
version: 0.0.1
# author: Nayan Parmar
homepage: https://github.com/Parmar24c/flutter_easy_routing

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
